# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-09-20 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20220914_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coche',
            options={'ordering': ('marca',)},
        ),
    ]
